from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1000, 494)
        self.logoutpic = QLabel(Form)
        self.logoutpic.setObjectName(u"logoutpic")
        self.logoutpic.setGeometry(QRect(30, 410, 41, 41))
        self.logoutpic.setPixmap(QPixmap(u"menuPage/images/logoutIcon.png"))
        self.pagestatus = QLabel(Form)
        self.pagestatus.setObjectName(u"pagestatus")
        self.pagestatus.setGeometry(QRect(460, 10, 351, 71))
        self.sharedrivebutton = QPushButton(Form)
        self.sharedrivebutton.setObjectName(u"sharedrivebutton")
        self.sharedrivebutton.setGeometry(QRect(70, 357, 121, 31))
        self.sharedrivebutton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.sharedrivepic = QLabel(Form)
        self.sharedrivepic.setObjectName(u"sharedrivepic")
        self.sharedrivepic.setGeometry(QRect(30, 350, 41, 41))
        self.sharedrivepic.setPixmap(QPixmap(u"menuPage/images/shareIcon.png"))
        self.mydrivebutton = QPushButton(Form)
        self.mydrivebutton.setObjectName(u"mydrivebutton")
        self.mydrivebutton.setGeometry(QRect(72, 297, 121, 31))
        self.mydrivebutton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.logoutbutton = QPushButton(Form)
        self.logoutbutton.setObjectName(u"logoutbutton")
        self.logoutbutton.setGeometry(QRect(70, 417, 121, 31))
        self.logoutbutton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.adddocbutton = QPushButton(Form)
        self.adddocbutton.setObjectName(u"adddocbutton")
        self.adddocbutton.setGeometry(QRect(72, 237, 121, 31))
        self.adddocbutton.setStyleSheet(u"\n"
"background-color: rgb(255, 255, 255);")
        self.adddocbutton.setCheckable(False)
        self.adddocbutton.setAutoRepeat(False)
        self.adddrivepic = QLabel(Form)
        self.adddrivepic.setObjectName(u"adddrivepic")
        self.adddrivepic.setGeometry(QRect(30, 230, 41, 41))
        self.adddrivepic.setPixmap(QPixmap(u"menuPage/images/add_icon.png"))
        self.mydrivepic = QLabel(Form)
        self.mydrivepic.setObjectName(u"mydrivepic")
        self.mydrivepic.setGeometry(QRect(30, 290, 41, 41))
        self.mydrivepic.setPixmap(QPixmap(u"menuPage/images/myDirveIcon.jpg"))
        self.menupic = QLabel(Form)
        self.menupic.setObjectName(u"menupic")
        self.menupic.setGeometry(QRect(60, 40, 151, 141))
        self.menupic.setPixmap(QPixmap(u"menuPage/images/menu_user_icon.png"))
        self.wallpaper = QLabel(Form)
        self.wallpaper.setObjectName(u"wallpaper")
        self.wallpaper.setGeometry(QRect(0, 0, 1000, 500))
        self.wallpaper.setPixmap(QPixmap(u"menuPage/images/menuBackground.png"))
        self.listWidget = QListWidget(Form)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(275, 130, 681, 331))
        self.wallpaper.raise_()
        self.logoutpic.raise_()
        self.pagestatus.raise_()
        self.sharedrivebutton.raise_()
        self.sharedrivepic.raise_()
        self.mydrivebutton.raise_()
        self.logoutbutton.raise_()
        self.adddocbutton.raise_()
        self.adddrivepic.raise_()   
        self.mydrivepic.raise_()
        self.menupic.raise_()
        self.listWidget.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.logoutpic.setText("")
        self.pagestatus.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">My Drive</span></p></body></html>", None))
        self.sharedrivebutton.setText(QCoreApplication.translate("Form", u"Share Drive", None))
        self.sharedrivepic.setText("")
        self.mydrivebutton.setText(QCoreApplication.translate("Form", u"My Drive", None))
        self.logoutbutton.setText(QCoreApplication.translate("Form", u"Log Out", None))
        self.adddocbutton.setText(QCoreApplication.translate("Form", u"Add Document", None))
        self.adddrivepic.setText("")
        self.mydrivepic.setText("")
        self.menupic.setText("")
        self.wallpaper.setText("")
    # retranslateUi